spring:
  datasource:
    url: jdbc:mysql://localhost/banzzokee?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: banzzokeeuser
    password: banzzokeepass
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true