server:
  port: 8080

spring:
  profiles:
    include:
      - jpa
      - s3
      - smtp
      - redis
      - elasticsearch

logging:
  level:
    org.springframework.data.elasticsearch.client:
      WIRE: TRACE