oauth2:
  client:
    registration:
      google:
        client_id: ${GOOGLE_CLIENT_ID}
        client_secret: ${GOOGLE_CLIENT_SECRET}
        redirect_uri: http://localhost:8080/api/auth/google/callback
        scope: email, profile