
name: auto CI CD

on:
  push:
    branches: [ "main", "develop" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main", "develop" ]
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Make environment file
        run: |
          cd ./src/main/resources
          mkdir properties
          cd properties
          touch ./env.properties
          echo "${{ secrets.ENV_PROPERTIES }}" > ./env.properties

      - name: Spring Boot Build
        run: ./gradlew bootJar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/banzzokee:${{ steps.meta.outputs.tags }}