name: auto CI CD

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Make environment file
        run: |
          cd ./src/main/resources
          mkdir properties
          cd properties
          touch ./env.properties
          echo ${{ secrets.ENV_PROPERTIES }} | base64 --decode > ./env.properties
          cat ./env.properties
        shell: bash

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/app/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/banzzokee:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/banzzokee:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker stop banzzokee
            sudo docker rm banzzokee
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/banzzokee:latest
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/banzzokee:latest
            sudo docker run -it -d --name banzzokee -p 8080:8080 --env-file ~/docker/.env --network bridge -v /home/ubuntu/config/fcm:/deploy/config ${{ secrets.DOCKERHUB_USERNAME }}/banzzokee:latest